services:
  chatbot:
    build:
      context: .
      dockerfile: chatbot/Dockerfile
    ports:
      - "8003:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      EMBEDDING_API_HOST: embedding-api:8000
      
  db:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata-2:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  embedding-api:
    build:
      context: .
      dockerfile: embedding_api/Dockerfile
    ports:
      - "8001:8000"
    environment:
      POSTGRES_CONNECTION_STRING: postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
      OPENAI_API_KEY: ${OPENAI_API_KEY}

  search-web:
    build:
      context: .
      dockerfile: search_web/Dockerfile
    ports:
      - "8002:8000"
    environment:
      EMBEDDING_API_HOST: embedding-api:8000

volumes:
  pgdata-2:
