services:
  chatbot:
    build:
      context: .
      dockerfile: chatbot/Dockerfile
    ports:
      - "8003:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
      EMBEDDING_API_HOST: embedding-api:8000
