services:
  chatbot:
    build:
      context: .
      dockerfile: chatbot/Dockerfile
    ports:
      - "8003:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      EMBEDDING_API_HOST: embedding-api:8000

  db:
    image: ghcr.io/encx/pgvector:med-data
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: med-record-2024

  embedding-api:
    build:
      context: .
      dockerfile: embedding_api/Dockerfile
    ports:
      - "8001:8000"
    environment:
      POSTGRES_CONNECTION_STRING: postgresql://postgres:med-record-2024@db:5432/postgres
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}

  search-web:
    build:
      context: .
      dockerfile: search_web/Dockerfile
    ports:
      - "8002:8000"
    environment:
      EMBEDDING_API_HOST: embedding-api:8000